# Generated by Django 4.2.6 on 2025-01-24 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_schedule_patient_remove_visit_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='api.schedule'),
        ),
    ]
