# Generated by Django 4.2.6 on 2025-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_visit_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='reting',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
