# Generated by Django 4.2.6 on 2025-01-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_visit_reting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='reting',
            new_name='rating',
        ),
    ]
