# Generated by Django 4.2.6 on 2025-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_reting_visit_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='rating_set',
            field=models.BooleanField(default=0),
        ),
    ]
