# Generated by Django 4.2.6 on 2025-01-25 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_visit_rating_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.doctor'),
        ),
    ]
