# Generated by Django 4.2.6 on 2025-01-25 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_visit_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='doctor',
        ),
    ]
